apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
  namespace: test
  annotations:
    # metric-config.pods.istio-requests-total.prometheus/per-replica: "true"
    metric-config.external.istio-requests-total.prometheus/prometheus-server: http://prometheus-server.infra.svc
    metric-config.external.istio-requests-total.prometheus/query: |
      sum(
          rate(
              istio_requests_total{
                destination_workload="podinfo",
                destination_workload_namespace="test",
                reporter="destination"
              }[2m]
          )
      ) /
      count(
        count(
          container_memory_usage_bytes{
            namespace="test",
          pod=~"podinfo.*"
          }
        ) by (pod)
      )
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: podinfo
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metric:
        name: istio-requests-total
        selector:
          matchLabels:
            type: prometheus
      target:
        type: AverageValue
        averageValue: "10"